define aunt = Character('Тётя Люба', color="#7cb00c")
define stasik = Character('Стас', color="#0e2c9be7")
define sveta = Character('Света', color="#ba09bd")
define kristina = Character('Кристина', color="#b5651d")
define direkt = Character('Директор', color="#ff0000")
define artem = Character('Артём', color="#1e90ff")
define student = Character('Ученик', color="#808080")
define student1 = Character('Ученик 1', color="#908080")
define student2 = Character('Ученик 2', color="#808780")
define student3 = Character('Ученик 3', color="#801080")
define elena = Character('Елена Петровна', color="#ff69b4")
